//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourceManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResourceManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying change.
        /// </summary>
        internal static string ChangingCulture {
            get {
                return ResourceManager.GetString("ChangingCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing culture completed.
        /// </summary>
        internal static string ChangingCultureCompleted {
            get {
                return ResourceManager.GetString("ChangingCultureCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESX Manager.
        /// </summary>
        internal static string ClientTitle {
            get {
                return ResourceManager.GetString("ClientTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close solution.
        /// </summary>
        internal static string CloseSolution {
            get {
                return ResourceManager.GetString("CloseSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure database.
        /// </summary>
        internal static string CreateDatabase {
            get {
                return ResourceManager.GetString("CreateDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database successfully created..
        /// </summary>
        internal static string CreatedDatabaseSuccess {
            get {
                return ResourceManager.GetString("CreatedDatabaseSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        internal static string Cultures {
            get {
                return ResourceManager.GetString("Cultures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        internal static string Database {
            get {
                return ResourceManager.GetString("Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database does not seem to be configured. Please check configuration..
        /// </summary>
        internal static string DataBaseNotConfigured {
            get {
                return ResourceManager.GetString("DataBaseNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database does not exist..
        /// </summary>
        internal static string DatabaseNotExists {
            get {
                return ResourceManager.GetString("DatabaseNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        internal static string Documentation {
            get {
                return ResourceManager.GetString("Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has been occurred. {0}. Please see error.txt for details..
        /// </summary>
        internal static string ErrorTextDefault {
            get {
                return ResourceManager.GetString("ErrorTextDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel-Document|*.xlsx.
        /// </summary>
        internal static string ExcelFileFilter {
            get {
                return ResourceManager.GetString("ExcelFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel-Document (*.xls,*.xlsx)|*.xls;*.xlsx.
        /// </summary>
        internal static string ExcelImportFileFilter {
            get {
                return ResourceManager.GetString("ExcelImportFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export comments.
        /// </summary>
        internal static string ExportComments {
            get {
                return ResourceManager.GetString("ExportComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export missing entries only.
        /// </summary>
        internal static string ExportDiff {
            get {
                return ResourceManager.GetString("ExportDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Excel.
        /// </summary>
        internal static string ExportToExcel {
            get {
                return ResourceManager.GetString("ExportToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Excel (missing entries only).
        /// </summary>
        internal static string ExportToExcelDiff {
            get {
                return ResourceManager.GetString("ExportToExcelDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For further information click here.
        /// </summary>
        internal static string HelpSetupDatabase {
            get {
                return ResourceManager.GetString("HelpSetupDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from Excel.
        /// </summary>
        internal static string ImportFromExcel {
            get {
                return ResourceManager.GetString("ImportFromExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include projects without translations.
        /// </summary>
        internal static string IncludeProjectsWithoutTranslations {
            get {
                return ResourceManager.GetString("IncludeProjectsWithoutTranslations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading solution.
        /// </summary>
        internal static string LoadingSolution {
            get {
                return ResourceManager.GetString("LoadingSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} entries which don`t exist in &apos;{1}&apos;.
        /// </summary>
        internal static string NotExistingInLanguage {
            get {
                return ResourceManager.GetString("NotExistingInLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open solution.
        /// </summary>
        internal static string OpenSolution {
            get {
                return ResourceManager.GetString("OpenSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        internal static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project &apos;{0}&apos; does not exist in this solution..
        /// </summary>
        internal static string ProjectUnknownException {
            get {
                return ResourceManager.GetString("ProjectUnknownException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource files have been changed. Save changes to files?.
        /// </summary>
        internal static string SaveChangesQuestion {
            get {
                return ResourceManager.GetString("SaveChangesQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        internal static string SaveChangesTitle {
            get {
                return ResourceManager.GetString("SaveChangesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save resource files.
        /// </summary>
        internal static string SaveResources {
            get {
                return ResourceManager.GetString("SaveResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving resource files.
        /// </summary>
        internal static string SavingResourceFiles {
            get {
                return ResourceManager.GetString("SavingResourceFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource files saved.
        /// </summary>
        internal static string SavingResourceFilesCompleted {
            get {
                return ResourceManager.GetString("SavingResourceFilesCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching translations in database.
        /// </summary>
        internal static string SearchingTranslations {
            get {
                return ResourceManager.GetString("SearchingTranslations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} texts translated..
        /// </summary>
        internal static string SearchingTranslationsResult {
            get {
                return ResourceManager.GetString("SearchingTranslationsResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching translations in database ({0}/{1}).
        /// </summary>
        internal static string SerachingTranslationsProcess {
            get {
                return ResourceManager.GetString("SerachingTranslationsProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        internal static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose language.
        /// </summary>
        internal static string SetCulture {
            get {
                return ResourceManager.GetString("SetCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure database.
        /// </summary>
        internal static string SetupDatabase {
            get {
                return ResourceManager.GetString("SetupDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store all translations to database.
        /// </summary>
        internal static string StoreAllTranslations {
            get {
                return ResourceManager.GetString("StoreAllTranslations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storing translations.
        /// </summary>
        internal static string StoringTranslations {
            get {
                return ResourceManager.GetString("StoringTranslations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storing translations completed.
        /// </summary>
        internal static string StoringTranslationsCompleted {
            get {
                return ResourceManager.GetString("StoringTranslationsCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test connection.
        /// </summary>
        internal static string TestConnection {
            get {
                return ResourceManager.GetString("TestConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully connected to database..
        /// </summary>
        internal static string TestConnectionSuccess {
            get {
                return ResourceManager.GetString("TestConnectionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate.
        /// </summary>
        internal static string Translate {
            get {
                return ResourceManager.GetString("Translate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto translate.
        /// </summary>
        internal static string TranslateAuto {
            get {
                return ResourceManager.GetString("TranslateAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translates missing texts by using already translated texts in a database. For details see ? -&gt; Documentation..
        /// </summary>
        internal static string TranslateToolTip {
            get {
                return ResourceManager.GetString("TranslateToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translations.
        /// </summary>
        internal static string Translations {
            get {
                return ResourceManager.GetString("Translations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual-Studio Solution|*.sln.
        /// </summary>
        internal static string VSSolutionFileFilter {
            get {
                return ResourceManager.GetString("VSSolutionFileFilter", resourceCulture);
            }
        }
    }
}
