//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourceManager.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResourceManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Adjust layout ähnelt.
        /// </summary>
        internal static string AutoAdjustLayout {
            get {
                return ResourceManager.GetString("AutoAdjustLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Applying change ähnelt.
        /// </summary>
        internal static string ChangingCulture {
            get {
                return ResourceManager.GetString("ChangingCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Changing culture completed ähnelt.
        /// </summary>
        internal static string ChangingCultureCompleted {
            get {
                return ResourceManager.GetString("ChangingCultureCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die RESX Manager ähnelt.
        /// </summary>
        internal static string ClientTitle {
            get {
                return ResourceManager.GetString("ClientTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close solution ähnelt.
        /// </summary>
        internal static string CloseSolution {
            get {
                return ResourceManager.GetString("CloseSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Configure database ähnelt.
        /// </summary>
        internal static string CreateDatabase {
            get {
                return ResourceManager.GetString("CreateDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Database successfully created. ähnelt.
        /// </summary>
        internal static string CreatedDatabaseSuccess {
            get {
                return ResourceManager.GetString("CreatedDatabaseSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Languages ähnelt.
        /// </summary>
        internal static string Cultures {
            get {
                return ResourceManager.GetString("Cultures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Database ähnelt.
        /// </summary>
        internal static string Database {
            get {
                return ResourceManager.GetString("Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Database does not seem to be configured. Please check configuration. ähnelt.
        /// </summary>
        internal static string DataBaseNotConfigured {
            get {
                return ResourceManager.GetString("DataBaseNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Database does not exist. ähnelt.
        /// </summary>
        internal static string DatabaseNotExists {
            get {
                return ResourceManager.GetString("DatabaseNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Documentation ähnelt.
        /// </summary>
        internal static string Documentation {
            get {
                return ResourceManager.GetString("Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An error has been occurred. {0}. Please see error.txt for details. ähnelt.
        /// </summary>
        internal static string ErrorTextDefault {
            get {
                return ResourceManager.GetString("ErrorTextDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Excel-Document|*.xlsx ähnelt.
        /// </summary>
        internal static string ExcelFileFilter {
            get {
                return ResourceManager.GetString("ExcelFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Excel-Document (*.xls,*.xlsx)|*.xls;*.xlsx ähnelt.
        /// </summary>
        internal static string ExcelImportFileFilter {
            get {
                return ResourceManager.GetString("ExcelImportFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exit ähnelt.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export ähnelt.
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export comments ähnelt.
        /// </summary>
        internal static string ExportComments {
            get {
                return ResourceManager.GetString("ExportComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export culture to Excel ähnelt.
        /// </summary>
        internal static string ExportCulture {
            get {
                return ResourceManager.GetString("ExportCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export cultures to Excel ähnelt.
        /// </summary>
        internal static string ExportCulturePair {
            get {
                return ResourceManager.GetString("ExportCulturePair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export missing entries only ähnelt.
        /// </summary>
        internal static string ExportDiff {
            get {
                return ResourceManager.GetString("ExportDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export file group to Excel ähnelt.
        /// </summary>
        internal static string ExportFileGroup {
            get {
                return ResourceManager.GetString("ExportFileGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export project to Excel ähnelt.
        /// </summary>
        internal static string ExportProjectToExcel {
            get {
                return ResourceManager.GetString("ExportProjectToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export to Excel ähnelt.
        /// </summary>
        internal static string ExportToExcel {
            get {
                return ResourceManager.GetString("ExportToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export to Excel (missing entries only) ähnelt.
        /// </summary>
        internal static string ExportToExcelDiff {
            get {
                return ResourceManager.GetString("ExportToExcelDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File ähnelt.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die For further information click here ähnelt.
        /// </summary>
        internal static string HelpSetupDatabase {
            get {
                return ResourceManager.GetString("HelpSetupDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore WinForms internal resources (&quot; &gt;&gt; &quot;).
        /// </summary>
        internal static string IgnoreInternalResources {
            get {
                return ResourceManager.GetString("IgnoreInternalResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import ähnelt.
        /// </summary>
        internal static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import from Excel ähnelt.
        /// </summary>
        internal static string ImportFromExcel {
            get {
                return ResourceManager.GetString("ImportFromExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Include projects without translations ähnelt.
        /// </summary>
        internal static string IncludeProjectsWithoutTranslations {
            get {
                return ResourceManager.GetString("IncludeProjectsWithoutTranslations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loading solution ähnelt.
        /// </summary>
        internal static string LoadingSolution {
            get {
                return ResourceManager.GetString("LoadingSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} entries which don`t exist in &apos;{1}&apos; ähnelt.
        /// </summary>
        internal static string NotExistingInLanguage {
            get {
                return ResourceManager.GetString("NotExistingInLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open ähnelt.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open solution ähnelt.
        /// </summary>
        internal static string OpenSolution {
            get {
                return ResourceManager.GetString("OpenSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projects ähnelt.
        /// </summary>
        internal static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The project &apos;{0}&apos; does not exist in this solution. ähnelt.
        /// </summary>
        internal static string ProjectUnknownException {
            get {
                return ResourceManager.GetString("ProjectUnknownException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Refresh ähnelt.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Resource files have been changed. Save changes to files? ähnelt.
        /// </summary>
        internal static string SaveChangesQuestion {
            get {
                return ResourceManager.GetString("SaveChangesQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save changes ähnelt.
        /// </summary>
        internal static string SaveChangesTitle {
            get {
                return ResourceManager.GetString("SaveChangesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save resource files ähnelt.
        /// </summary>
        internal static string SaveResources {
            get {
                return ResourceManager.GetString("SaveResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Saving resource files ähnelt.
        /// </summary>
        internal static string SavingResourceFiles {
            get {
                return ResourceManager.GetString("SavingResourceFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Resource files saved ähnelt.
        /// </summary>
        internal static string SavingResourceFilesCompleted {
            get {
                return ResourceManager.GetString("SavingResourceFilesCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Searching translations in database ähnelt.
        /// </summary>
        internal static string SearchingTranslations {
            get {
                return ResourceManager.GetString("SearchingTranslations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} texts translated. ähnelt.
        /// </summary>
        internal static string SearchingTranslationsResult {
            get {
                return ResourceManager.GetString("SearchingTranslationsResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Searching translations in database ({0}/{1}) ähnelt.
        /// </summary>
        internal static string SerachingTranslationsProcess {
            get {
                return ResourceManager.GetString("SerachingTranslationsProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Server ähnelt.
        /// </summary>
        internal static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose language ähnelt.
        /// </summary>
        internal static string SetCulture {
            get {
                return ResourceManager.GetString("SetCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Configure database ähnelt.
        /// </summary>
        internal static string SetupDatabase {
            get {
                return ResourceManager.GetString("SetupDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Store all translations to database ähnelt.
        /// </summary>
        internal static string StoreAllTranslations {
            get {
                return ResourceManager.GetString("StoreAllTranslations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Storing translations ähnelt.
        /// </summary>
        internal static string StoringTranslations {
            get {
                return ResourceManager.GetString("StoringTranslations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Storing translations completed ähnelt.
        /// </summary>
        internal static string StoringTranslationsCompleted {
            get {
                return ResourceManager.GetString("StoringTranslationsCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Test connection ähnelt.
        /// </summary>
        internal static string TestConnection {
            get {
                return ResourceManager.GetString("TestConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Successfully connected to database. ähnelt.
        /// </summary>
        internal static string TestConnectionSuccess {
            get {
                return ResourceManager.GetString("TestConnectionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Translate ähnelt.
        /// </summary>
        internal static string Translate {
            get {
                return ResourceManager.GetString("Translate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto translate ähnelt.
        /// </summary>
        internal static string TranslateAuto {
            get {
                return ResourceManager.GetString("TranslateAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Translates missing texts by using already translated texts in a database. For details see ? -&gt; Documentation. ähnelt.
        /// </summary>
        internal static string TranslateToolTip {
            get {
                return ResourceManager.GetString("TranslateToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Translations ähnelt.
        /// </summary>
        internal static string Translations {
            get {
                return ResourceManager.GetString("Translations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Visual-Studio Solution|*.sln ähnelt.
        /// </summary>
        internal static string VSSolutionFileFilter {
            get {
                return ResourceManager.GetString("VSSolutionFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The solution &apos;{0}&apos; does not contain any culture. Have you loaded the correct solution? ähnelt.
        /// </summary>
        internal static string WarningNoCultures {
            get {
                return ResourceManager.GetString("WarningNoCultures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The solution &apos;{0}&apos; does not contain any project. Have you loaded the correct solution? ähnelt.
        /// </summary>
        internal static string WarningNoProjects {
            get {
                return ResourceManager.GetString("WarningNoProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warning ähnelt.
        /// </summary>
        internal static string WarningOpenSolutionTitle {
            get {
                return ResourceManager.GetString("WarningOpenSolutionTitle", resourceCulture);
            }
        }
    }
}
